### ISSUE TITLE
This is rad!

### ISSUE THREAD

**Issue by tillkruss** [naxvog/wpr-redis#1]
Have you had any issues with using Redis for WP Rocket or is this stable?

**Comment by naxvog** [comment]
_Crazy thing I need to watch my own projects in order to get notified - sorry didn't see your issue._

As far as I know and tested this is stable but I am not currently using it in my production environments.
There are currently two "issues"
* it lacks connection options to clusters
* using the WP Rocket nginx configuration this is slower than the nginx `try_files` directive but there is a nginx redis module that could theoretically be used to be just as fast
